import Head from 'next/head'
import {BsFillMoonStarsFill, BsFillSunFill} from 'react-icons/bs'
import {AiFillInstagram, AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import Image from 'next/image'
import webDev from '../public/WebDev.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import { useState } from 'react'

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={ darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className=' min-h-screen'>
          <nav className=' py-10 mb-12 flex justify-between'>
            <h1 className=' text-xl font-burtons dark:text-gray-200'>DevPavanSantosh</h1>
            <ul className=' flex items-center'>
              {darkMode ? <li>
                <BsFillSunFill className=' cursor-pointer text-2xl text-gray-200' onClick={() => setDarkMode(!darkMode)}/>
              </li> : <li>
                <BsFillMoonStarsFill className=' cursor-pointer text-2xl' onClick={() => setDarkMode(!darkMode)}/>
              </li>}
              <li>
                <a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 dark:from-violet-500 dark:to-purple-500' href="https://drive.google.com/file/d/1XW7GFCdsv8jYyWwYNJOqRT9bd_san8tO/view?usp=sharing" target={"_blank"} rel="noreferrer" >Resume</a>
              </li>
            </ul>
          </nav>

          <div className=' text-center p-10'>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-purple-600'>
              Pavan Santosh
            </h2>
            <h3 className=' text-2xl py-2 md:text-3xl  dark:text-gray-200'>
              Fullstack Developer
            </h3>
            <p className=' text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto  dark:text-gray-200'>
              Currently working in Affinsys.ai as a Software Engineer. Feel free to join me down below😊.
            </p>
          </div>
          <div className=' text-3xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href="https://www.linkedin.com/in/pavan-santosh/"><AiFillLinkedin/></a>
            <a href="https://github.com/pavansantosh-ps"><AiFillGithub/></a>
            <a href="https://www.instagram.com/pavann_santosh/"><AiFillInstagram/></a>
          </div>

          <div className=' relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 mx-auto overflow-hidden md:h-96 md:w-96 dark:from-purple-500'>
            <Image src={webDev} layout = "fill" objectFit="cover"/>
          </div>
        </section>


        <section>
          <div>
            <h3 className=' text-3xl py-1 dark:text-white'>
              About me:
            </h3>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              Hey everyone👋! I am Pavan santosh. I am a web development enthusiast. 
              My technical journey started in my college years. 
              I worked on few projects using techs such as 
              <span className='text-teal-500 dark:text-purple-500'> React js</span>,<span className='text-teal-500 dark:text-purple-500'>next js</span>,
              <span className='text-teal-500 dark:text-purple-500'>Angular </span>. 
              I also worked on the backend using 
              <span className='text-teal-500 dark:text-purple-500'> node js</span>. 
              I am also an 
              <span className='text-teal-500 dark:text-purple-500'> AWS certified cloud practitioner</span>. 
            </p>
            <p className=' text-md py-2 leading-8 text-gray-800  dark:text-gray-200'>
              I am looking forward to expand my knowledge.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className=' text-center shadow-xl pd-10 rounded-xl my-10 flex-1 dark:bg-gray-200 dark:shadow-slate-700'>
              <Image src={code} width={100} height={100}></Image>
              <h3 className=' text-lg font-medium pt-8 pb-2'>Programming languages</h3>
              <p className='py-2'>Decent knowledge on multiple Programming languages</p>
              <h4 className='py-4 text-teal-500'>Languages known</h4>
              <p className='text-gray-600 py-1'>Java</p>
              <p className='text-gray-600 py-1'>Javascript</p>
              <p className='text-gray-600 py-1'>python</p>
            </div>
            <div className=' text-center shadow-xl pd-10 rounded-xl my-10 flex-1 dark:bg-gray-200 dark:shadow-slate-700'>
              <Image src={design} width={100} height={100}></Image>
              <h3 className=' text-lg font-medium pt-8 pb-2'>Fullstack Development</h3>
              <p className='py-2'>Created multiple applications</p>
              <h4 className='py-4 text-teal-500'>Technology used</h4>
              <p className='text-gray-600 py-1'>React js</p>
              <p className='text-gray-600 py-1'>Next js</p>
              <p className='text-gray-600 py-1'>Angular</p>
              <p className='text-gray-600 py-1'>Node js</p>
            </div>
            <div className=' text-center shadow-xl pd-10 rounded-xl my-10 flex-1 dark:bg-gray-200 dark:shadow-slate-700'>
              <Image src={consulting} width={100} height={100}></Image>
              <h3 className=' text-lg font-medium pt-8 pb-2'> Certificates/Achievements</h3>
              <p className='py-2'>Completed and acheieved few certificates</p>
              <h4 className='py-4 text-teal-500'>Certificates</h4>
              <a href="https://www.credly.com/badges/98e49e54-71c2-4542-a36e-7d2b613002df?source=linked_in_profile" target={"_blank"} rel="noreferrer" ><p className='text-gray-600 py-1'>Aws Cloud Practitionar</p></a>
              <a href="https://www.hackerrank.com/certificates/a23ea8a0571b" target={"_blank"} rel="noreferrer" ><p className='text-gray-600 py-1'>HackerRank React Basics</p></a>
              <a href="https://www.cloudskillsboost.google/public_profiles/652b23db-5467-482b-b9c7-4488a89abd9d" target={"_blank"} rel="noreferrer" ><p className='text-gray-600 py-1'>Learn to Earn GoogleCloud</p></a>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className=' text-3xl py-1 dark:text-white'>Portfolio:</h3>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              You can find my work below😊.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className=' basis-1/3 flex-1'>
              <a href="https://pavansantosh-ps.github.io/SortingVisualizer/"  target={"_blank"} rel="noreferrer" ><Image src={web2} className='rounded-lg object-contain cursor-pointer sm:object-cover'layout="responsive"/></a>
            </div>
            <div className=' basis-1/3 flex-1'>
              <a href="https://github.com/pavansantosh-ps/MedEx"  target={"_blank"} rel="noreferrer" ><Image src={web4} className='rounded-lg object-contain cursor-pointer sm:object-cover' layout="responsive"/></a>
            </div>
            <div className=' basis-1/3 flex-1'>
              <a href="https://pavansantosh-ps.github.io/movie-quotes/" target={"_blank"} rel="noreferrer"><Image src={web1} className='rounded-lg object-contain cursor-pointer sm:object-cover' layout="responsive"/></a>
            </div>
            <div className=' basis-1/3 flex-1'>
              <a href="https://pavansantosh-ps.github.io/BankingApplication-TSF/"  target={"_blank"} rel="noreferrer" ><Image src={web3} className='rounded-lg object-contain cursor-pointer sm:object-cover' layout="responsive"/></a>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
